# Goal: get all unique tconst for relevant filter

## Import data

In [5]:
import pandas as pd

In [6]:
df_title_basics = pd.read_csv("Data/title.principals/title.basics.csv")

In [7]:
df_title_basics.shape

(11057208, 9)

In [8]:
df_title_basics.head()

,tconst,titleType,primaryTitle,originalTitle,isAdult,startYear,endYear,runtimeMinutes,genres
0,tt0000001,short,Carmencita,Carmencita,0.0,1894.0,\N,1,"Documentary,Short"
1,tt0000002,short,Le clown et ses chiens,Le clown et ses chiens,0.0,1892.0,\N,5,"Animation,Short"
2,tt0000003,short,Pauvre Pierrot,Pauvre Pierrot,0.0,1892.0,\N,5,"Animation,Comedy,Romance"
3,tt0000004,short,Un bon bock,Un bon bock,0.0,1892.0,\N,12,"Animation,Short"
4,tt0000005,short,Blacksmith Scene,Blacksmith Scene,0.0,1893.0,\N,1,"Comedy,Short"

In [9]:
df_title_basics.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11057208 entries, 0 to 11057207
Data columns (total 9 columns):
 #   Column          Dtype
---  ------          -----
 0   tconst          object
 1   titleType       object
 2   primaryTitle    object
 3   originalTitle   object
 4   isAdult         float64
 5   startYear       float64
 6   endYear         object
 7   runtimeMinutes  object
 8   genres          object
dtypes: float64(2), object(7)
memory usage: 759.2+ MB

In [10]:
df_title_basics["titleType"].unique()

array(['short', 'movie', 'tvShort', 'tvMovie', 'tvEpisode', 'tvSeries',
       'tvMiniSeries', 'tvSpecial', 'video', 'videoGame', 'tvPilot'],
      dtype=object)

In [11]:
movie_mask = df_title_basics["titleType"].isin(['movie', 'tvMovie'])
year_mask = df_title_basics["startYear"] >= 1950

combined_mask = (movie_mask) & (year_mask)

In [12]:
df_title_basics_filtered = df_title_basics[combined_mask]
df_title_basics_filtered.shape

(664040, 9)

In [10]:
df_title_basics_filtered.describe(include="all")

,tconst,titleType,primaryTitle,originalTitle,isAdult,startYear,endYear,runtimeMinutes,genres
count,664040,664040,664038,664038,664040.000000,664040.000000,664040,664040,664040
unique,664040,2,588123,599933,NaN,NaN,1,523,1458
top,tt0011801,movie,Macbeth,Macbeth,NaN,NaN,\N,\N,Documentary
freq,1,520432,64,63,NaN,NaN,664040,171728,131274
mean,NaN,NaN,NaN,NaN,0.013913,2000.506917,NaN,NaN,NaN
std,NaN,NaN,NaN,NaN,0.117131,19.917583,NaN,NaN,NaN
min,NaN,NaN,NaN,NaN,0.000000,1950.000000,NaN,NaN,NaN
25%,NaN,NaN,NaN,NaN,0.000000,1986.000000,NaN,NaN,NaN
50%,NaN,NaN,NaN,NaN,0.000000,2008.000000,NaN,NaN,NaN
75%,NaN,NaN,NaN,NaN,0.000000,2017.000000,NaN,NaN,NaN
max,NaN,NaN,NaN,NaN,1.000000,2031.000000,NaN,NaN,NaN

In [11]:
df_title_basics_filtered["tconst"]

11632       tt0011801
13077       tt0013274
15172       tt0015414
15480       tt0015724
21267       tt0021617
              ...
11057126    tt9916680
11057131    tt9916692
11057138    tt9916706
11057148    tt9916730
11057158    tt9916754
Name: tconst, Length: 664040, dtype: object

In [12]:
#df_title_basics_filtered["tconst"].to_csv("Data/tconst.csv", index= False)

In [13]:
pd.Series.to_csv?

Signature:
pd.Series.to_csv(
    self,
    path_or_buf: 'FilePath | WriteBuffer[bytes] | WriteBuffer[str] | None' = None,
    *,
    sep: 'str' = ',',
    na_rep: 'str' = '',
    float_format: 'str | Callable | None' = None,
    columns: 'Sequence[Hashable] | None' = None,
    header: 'bool_t | list[str]' = True,
    index: 'bool_t' = True,
    index_label: 'IndexLabel | None' = None,
    mode: 'str' = 'w',
    encoding: 'str | None' = None,
    compression: 'CompressionOptions' = 'infer',
    quoting: 'int | None' = None,
    quotechar: 'str' = '"',
    lineterminator: 'str | None' = None,
    chunksize: 'int | None' = None,
    date_format: 'str | None' = None,
    doublequote: 'bool_t' = True,
    escapechar: 'str | None' = None,
    decimal: 'str' = '.',
    errors: 'OpenFileErrors' = 'strict',
    storage_options: 'StorageOptions | None' = None,
) -> 'str | None'
Docstring:
Write object to a comma-separated values (csv) file.

Parameters
----------
path_or_buf : str, path object, file-like object, or None, default None
    String, path object (implementing os.PathLike[str]), or file-like
    object implementing a write() function. If None, the result is
    returned as a string. If a non-binary file object is passed, it should
    be opened with `newline=''`, disabling universal newlines. If a binary
    file object is passed, `mode` might need to contain a `'b'`.
sep : str, default ','
    String of length 1. Field delimiter for the output file.
na_rep : str, default ''
    Missing data representation.
float_format : str, Callable, default None
    Format string for floating point numbers. If a Callable is given, it takes
    precedence over other numeric formatting parameters, like decimal.
columns : sequence, optional
    Columns to write.
header : bool or list of str, default True
    Write out the column names. If a list of strings is given it is
    assumed to be aliases for the column names.
index : bool, default True
    Write row names (index).
index_label : str or sequence, or False, default None
    Column label for index column(s) if desired. If None is given, and
    `header` and `index` are True, then the index names are used. A
    sequence should be given if the object uses MultiIndex. If
    False do not print fields for index names. Use index_label=False
    for easier importing in R.
mode : {'w', 'x', 'a'}, default 'w'
    Forwarded to either `open(mode=)` or `fsspec.open(mode=)` to control
    the file opening. Typical values include:

    - 'w', truncate the file first.
    - 'x', exclusive creation, failing if the file already exists.
    - 'a', append to the end of file if it exists.

encoding : str, optional
    A string representing the encoding to use in the output file,
    defaults to 'utf-8'. `encoding` is not supported if `path_or_buf`
    is a non-binary file object.
compression : str or dict, default 'infer'
    For on-the-fly compression of the output data. If 'infer' and 'path_or_buf' is
    path-like, then detect compression from the following extensions: '.gz',
    '.bz2', '.zip', '.xz', '.zst', '.tar', '.tar.gz', '.tar.xz' or '.tar.bz2'
    (otherwise no compression).
    Set to ``None`` for no compression.
    Can also be a dict with key ``'method'`` set
    to one of {``'zip'``, ``'gzip'``, ``'bz2'``, ``'zstd'``, ``'xz'``, ``'tar'``} and
    other key-value pairs are forwarded to
    ``zipfile.ZipFile``, ``gzip.GzipFile``,
    ``bz2.BZ2File``, ``zstandard.ZstdCompressor``, ``lzma.LZMAFile`` or
    ``tarfile.TarFile``, respectively.
    As an example, the following could be passed for faster compression and to create
    a reproducible gzip archive:
    ``compression={'method': 'gzip', 'compresslevel': 1, 'mtime': 1}``.

    .. versionadded:: 1.5.0
        Added support for `.tar` files.

       May be a dict with key 'method' as compression mode
       and other entries as additional compression options if
       compression mode is 'zip'.

       Passing compression options as keys in dict is
       supported for compression modes 'gzip', 'bz2', 'zstd', and 'zip'.
quoting : optional constant from csv module
    Defaults to csv.QUOTE_MINIMAL. If you have set a `float_format`
    then floats are converted to strings and thus csv.QUOTE_NONNUMERIC
    will treat them as non-numeric.
quotechar : str, default '\"'
    String of length 1. Character used to quote fields.
lineterminator : str, optional
    The newline character or character sequence to use in the output
    file. Defaults to `os.linesep`, which depends on the OS in which
    this method is called ('\\n' for linux, '\\r\\n' for Windows, i.e.).

    .. versionchanged:: 1.5.0

        Previously was line_terminator, changed for consistency with
        read_csv and the standard library 'csv' module.

chunksize : int or None
    Rows to write at a time.
date_format : str, default None
    Format string for datetime objects.
doublequote : bool, default True
    Control quoting of `quotechar` inside a field.
escapechar : str, default None
    String of length 1. Character used to escape `sep` and `quotechar`
    when appropriate.
decimal : str, default '.'
    Character recognized as decimal separator. E.g. use ',' for
    European data.
errors : str, default 'strict'
    Specifies how encoding and decoding errors are to be handled.
    See the errors argument for :func:`open` for a full list
    of options.

storage_options : dict, optional
    Extra options that make sense for a particular storage connection, e.g.
    host, port, username, password, etc. For HTTP(S) URLs the key-value pairs
    are forwarded to ``urllib.request.Request`` as header options. For other
    URLs (e.g. starting with "s3://", and "gcs://") the key-value pairs are
    forwarded to ``fsspec.open``. Please see ``fsspec`` and ``urllib`` for more
    details, and for more examples on storage options refer `here
    <https://pandas.pydata.org/docs/user_guide/io.html?
    highlight=storage_options#reading-writing-remote-files>`_.

Returns
-------
None or str
    If path_or_buf is None, returns the resulting csv format as a
    string. Otherwise returns None.

See Also
--------
read_csv : Load a CSV file into a DataFrame.
to_excel : Write DataFrame to an Excel file.

Examples
--------
Create 'out.csv' containing 'df' without indices

>>> df = pd.DataFrame({'name': ['Raphael', 'Donatello'],
...                    'mask': ['red', 'purple'],
...                    'weapon': ['sai', 'bo staff']})
>>> df.to_csv('out.csv', index=False)  # doctest: +SKIP

Create 'out.zip' containing 'out.csv'

>>> df.to_csv(index=False)
'name,mask,weapon\nRaphael,red,sai\nDonatello,purple,bo staff\n'
>>> compression_opts = dict(method='zip',
...                         archive_name='out.csv')  # doctest: +SKIP
>>> df.to_csv('out.zip', index=False,
...           compression=compression_opts)  # doctest: +SKIP

To write a csv file to a new folder or nested folder you will first
need to create it using either Pathlib or os:

>>> from pathlib import Path  # doctest: +SKIP
>>> filepath = Path('folder/subfolder/out.csv')  # doctest: +SKIP
>>> filepath.parent.mkdir(parents=True, exist_ok=True)  # doctest: +SKIP
>>> df.to_csv(filepath)  # doctest: +SKIP

>>> import os  # doctest: +SKIP
>>> os.makedirs('folder/subfolder', exist_ok=True)  # doctest: +SKIP
>>> df.to_csv('folder/subfolder/out.csv')  # doctest: +SKIP
File:      /opt/homebrew/Caskroom/miniconda/base/envs/nf_base/lib/python3.9/site-packages/pandas/core/generic.py
Type:      function

In [14]:
df_title_basics_filtered.head()

,tconst,titleType,primaryTitle,originalTitle,isAdult,startYear,endYear,runtimeMinutes,genres
11632,tt0011801,movie,Tötet nicht mehr,Tötet nicht mehr,0.0,2019.0,\N,\N,"Action,Crime"
13077,tt0013274,movie,Istoriya grazhdanskoy voyny,Istoriya grazhdanskoy voyny,0.0,2021.0,\N,94,Documentary
15172,tt0015414,movie,La tierra de los toros,La tierra de los toros,0.0,2000.0,\N,60,\N
15480,tt0015724,movie,Dama de noche,Dama de noche,0.0,1993.0,\N,102,"Drama,Mystery,Romance"
21267,tt0021617,movie,Arizona Territory,Arizona Territory,0.0,1950.0,\N,56,Western

In [3]:
df_title_ratings = pd.read_csv("Data/title.principals/title.ratings.csv")

In [16]:
df_title_ratings.head()

      tconst  averageRating  numVotes
0  tt0000001            5.7      2082
1  tt0000002            5.6       280
2  tt0000003            6.5      2081
3  tt0000004            5.4       181
4  tt0000005            6.2      2819

In [19]:
df_title_ratings.sort_values(by="numVotes", ascending=False).head(20)

           tconst  averageRating  numVotes
83894   tt0111161            9.3   2937161
256157  tt0468569            9.0   2917451
669432  tt1375666            8.8   2590527
100658  tt0137523            8.8   2368583
446855  tt0944947            9.2   2340588
82794   tt0109830            8.8   2296848
83677   tt0110912            8.9   2255783
435748  tt0903747            9.5   2200576
407175  tt0816692            8.7   2154266
98427   tt0133093            8.7   2085691
47369   tt0068646            9.2   2047193
91711   tt0120737            8.9   2038566
116518  tt0167260            9.0   2009614
653975  tt1345836            8.4   1853805
86460   tt0114369            8.6   1831506
116519  tt0167261            8.8   1812054
843581  tt1853728            8.5   1725282
119094  tt0172495            8.5   1654447
460503  tt0993846            8.2   1616411
209716  tt0361748            8.4   1613462

In [20]:
import matplotlib.pyplot as plt
import seaborn as sns

In [22]:
plt.figure(figsize=(12,8))

sns.histplot(data=df_title_ratings, x="numVotes")

In [ ]:
df_title_ratings["numVotes"].describe()

In [6]:
bins = pd.IntervalIndex.from_tuples([(0, 1), (2, 5), (6, 10), (11, 50), (51, 100), (101, 1000), (1001, 3_000_000)])
bins

IntervalIndex([(0, 1], (2, 5], (6, 10], (11, 50], (51, 100], (101, 1000],
               (1001, 3000000]],
              dtype='interval[int64, right]')

In [8]:
df_title_ratings["numVotesCut"] = pd.cut(df_title_ratings["numVotes"], bins=bins)

In [10]:
df_title_ratings.groupby("numVotesCut").size()

/var/folders/4w/4tr10mrx69334wpfj60r7s3c0000gn/T/ipykernel_49799/3173473509.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  df_title_ratings.groupby("numVotesCut").size()

numVotesCut
(0, 1]                  0
(2, 5]              36354
(6, 10]            230248
(11, 50]           579810
(51, 100]          150122
(101, 1000]        276078
(1001, 3000000]     90753
dtype: int64

In [19]:
df_title_ratings.shape

(1473803, 4)

In [17]:
df_basic_ratings_merged_filtered = pd.merge(df_title_basics_filtered, df_title_ratings, how='left', on="tconst")

In [18]:
df_basic_ratings_merged_filtered.shape

(664040, 12)

In [20]:
df_basic_ratings_merged_filtered.head()

,tconst,titleType,primaryTitle,originalTitle,isAdult,startYear,endYear,runtimeMinutes,genres,averageRating,numVotes,numVotesCut
0,tt0011801,movie,Tötet nicht mehr,Tötet nicht mehr,0.0,2019.0,\N,\N,"Action,Crime",NaN,NaN,NaN
1,tt0013274,movie,Istoriya grazhdanskoy voyny,Istoriya grazhdanskoy voyny,0.0,2021.0,\N,94,Documentary,6.7,73.0,"(51.0, 100.0]"
2,tt0015414,movie,La tierra de los toros,La tierra de los toros,0.0,2000.0,\N,60,\N,5.4,17.0,"(11.0, 50.0]"
3,tt0015724,movie,Dama de noche,Dama de noche,0.0,1993.0,\N,102,"Drama,Mystery,Romance",6.5,30.0,"(11.0, 50.0]"
4,tt0021617,movie,Arizona Territory,Arizona Territory,0.0,1950.0,\N,56,Western,6.1,62.0,"(51.0, 100.0]"

In [23]:
df_basic_ratings_merged_filtered.groupby("numVotesCut").size()

/var/folders/4w/4tr10mrx69334wpfj60r7s3c0000gn/T/ipykernel_49799/2322572492.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  df_basic_ratings_merged_filtered.groupby("numVotesCut").size()

numVotesCut
(0, 1]                  0
(2, 5]               2418
(6, 10]             33823
(11, 50]           115704
(51, 100]           40156
(101, 1000]         92281
(1001, 3000000]     44342
dtype: int64

In [24]:
df_basic_ratings_merged_filtered["numVotesCut"].isna().sum()

335316

Signature:
pd.merge(
    left: 'DataFrame | Series',
    right: 'DataFrame | Series',
    how: 'MergeHow' = 'inner',
    on: 'IndexLabel | AnyArrayLike | None' = None,
    left_on: 'IndexLabel | AnyArrayLike | None' = None,
    right_on: 'IndexLabel | AnyArrayLike | None' = None,
    left_index: 'bool' = False,
    right_index: 'bool' = False,
    sort: 'bool' = False,
    suffixes: 'Suffixes' = ('_x', '_y'),
    copy: 'bool | None' = None,
    indicator: 'str | bool' = False,
    validate: 'str | None' = None,
) -> 'DataFrame'
Docstring:
Merge DataFrame or named Series objects with a database-style join.

A named Series object is treated as a DataFrame with a single named column.

The join is done on columns or indexes. If joining columns on
columns, the DataFrame indexes *will be ignored*. Otherwise if joining indexes
on indexes or indexes on a column or columns, the index will be passed on.
When performing a cross merge, no column specifications to merge on are
allowed.

.. warning::

    If both key columns contain rows where the key is a null value, those
    rows will be matched against each other. This is different from usual SQL
    join behaviour and can lead to unexpected results.

Parameters
----------
left : DataFrame or named Series
right : DataFrame or named Series
    Object to merge with.
how : {'left', 'right', 'outer', 'inner', 'cross'}, default 'inner'
    Type of merge to be performed.

    * left: use only keys from left frame, similar to a SQL left outer join;
      preserve key order.
    * right: use only keys from right frame, similar to a SQL right outer join;
      preserve key order.
    * outer: use union of keys from both frames, similar to a SQL full outer
      join; sort keys lexicographically.
    * inner: use intersection of keys from both frames, similar to a SQL inner
      join; preserve the order of the left keys.
    * cross: creates the cartesian product from both frames, preserves the order
      of the left keys.
on : label or list
    Column or index level names to join on. These must be found in both
    DataFrames. If `on` is None and not merging on indexes then this defaults
    to the intersection of the columns in both DataFrames.
left_on : label or list, or array-like
    Column or index level names to join on in the left DataFrame. Can also
    be an array or list of arrays of the length of the left DataFrame.
    These arrays are treated as if they are columns.
right_on : label or list, or array-like
    Column or index level names to join on in the right DataFrame. Can also
    be an array or list of arrays of the length of the right DataFrame.
    These arrays are treated as if they are columns.
left_index : bool, default False
    Use the index from the left DataFrame as the join key(s). If it is a
    MultiIndex, the number of keys in the other DataFrame (either the index
    or a number of columns) must match the number of levels.
right_index : bool, default False
    Use the index from the right DataFrame as the join key. Same caveats as
    left_index.
sort : bool, default False
    Sort the join keys lexicographically in the result DataFrame. If False,
    the order of the join keys depends on the join type (how keyword).
suffixes : list-like, default is ("_x", "_y")
    A length-2 sequence where each element is optionally a string
    indicating the suffix to add to overlapping column names in
    `left` and `right` respectively. Pass a value of `None` instead
    of a string to indicate that the column name from `left` or
    `right` should be left as-is, with no suffix. At least one of the
    values must not be None.
copy : bool, default True
    If False, avoid copy if possible.

    .. note::
        The `copy` keyword will change behavior in pandas 3.0.
        `Copy-on-Write
        <https://pandas.pydata.org/docs/dev/user_guide/copy_on_write.html>`__
        will be enabled by default, which means that all methods with a
        `copy` keyword will use a lazy copy mechanism to defer the copy and
        ignore the `copy` keyword. The `copy` keyword will be removed in a
        future version of pandas.

        You can already get the future behavior and improvements through
        enabling copy on write ``pd.options.mode.copy_on_write = True``
indicator : bool or str, default False
    If True, adds a column to the output DataFrame called "_merge" with
    information on the source of each row. The column can be given a different
    name by providing a string argument. The column will have a Categorical
    type with the value of "left_only" for observations whose merge key only
    appears in the left DataFrame, "right_only" for observations
    whose merge key only appears in the right DataFrame, and "both"
    if the observation's merge key is found in both DataFrames.

validate : str, optional
    If specified, checks if merge is of specified type.

    * "one_to_one" or "1:1": check if merge keys are unique in both
      left and right datasets.
    * "one_to_many" or "1:m": check if merge keys are unique in left
      dataset.
    * "many_to_one" or "m:1": check if merge keys are unique in right
      dataset.
    * "many_to_many" or "m:m": allowed, but does not result in checks.

Returns
-------
DataFrame
    A DataFrame of the two merged objects.

See Also
--------
merge_ordered : Merge with optional filling/interpolation.
merge_asof : Merge on nearest keys.
DataFrame.join : Similar method using indices.

Examples
--------
>>> df1 = pd.DataFrame({'lkey': ['foo', 'bar', 'baz', 'foo'],
...                     'value': [1, 2, 3, 5]})
>>> df2 = pd.DataFrame({'rkey': ['foo', 'bar', 'baz', 'foo'],
...                     'value': [5, 6, 7, 8]})
>>> df1
    lkey value
0   foo      1
1   bar      2
2   baz      3
3   foo      5
>>> df2
    rkey value
0   foo      5
1   bar      6
2   baz      7
3   foo      8

Merge df1 and df2 on the lkey and rkey columns. The value columns have
the default suffixes, _x and _y, appended.

>>> df1.merge(df2, left_on='lkey', right_on='rkey')
  lkey  value_x rkey  value_y
0  foo        1  foo        5
1  foo        1  foo        8
2  bar        2  bar        6
3  baz        3  baz        7
4  foo        5  foo        5
5  foo        5  foo        8

Merge DataFrames df1 and df2 with specified left and right suffixes
appended to any overlapping columns.

>>> df1.merge(df2, left_on='lkey', right_on='rkey',
...           suffixes=('_left', '_right'))
  lkey  value_left rkey  value_right
0  foo           1  foo            5
1  foo           1  foo            8
2  bar           2  bar            6
3  baz           3  baz            7
4  foo           5  foo            5
5  foo           5  foo            8

Merge DataFrames df1 and df2, but raise an exception if the DataFrames have
any overlapping columns.

>>> df1.merge(df2, left_on='lkey', right_on='rkey', suffixes=(False, False))
Traceback (most recent call last):
...
ValueError: columns overlap but no suffix specified:
    Index(['value'], dtype='object')

>>> df1 = pd.DataFrame({'a': ['foo', 'bar'], 'b': [1, 2]})
>>> df2 = pd.DataFrame({'a': ['foo', 'baz'], 'c': [3, 4]})
>>> df1
      a  b
0   foo  1
1   bar  2
>>> df2
      a  c
0   foo  3
1   baz  4

>>> df1.merge(df2, how='inner', on='a')
      a  b  c
0   foo  1  3

>>> df1.merge(df2, how='left', on='a')
      a  b  c
0   foo  1  3.0
1   bar  2  NaN

>>> df1 = pd.DataFrame({'left': ['foo', 'bar']})
>>> df2 = pd.DataFrame({'right': [7, 8]})
>>> df1
    left
0   foo
1   bar
>>> df2
    right
0   7
1   8

>>> df1.merge(df2, how='cross')
   left  right
0   foo      7
1   foo      8
2   bar      7
3   bar      8
File:      /opt/homebrew/Caskroom/miniconda/base/envs/nf_base/lib/python3.9/site-packages/pandas/core/reshape/merge.py
Type:      function

In [4]:
df_title_basics

NameError: name 'df_title_basics' is not defined

### tv-movies

What kind of films are in this category

In [14]:
df_title_basics_filtered.head()

,tconst,titleType,primaryTitle,originalTitle,isAdult,startYear,endYear,runtimeMinutes,genres
11632,tt0011801,movie,Tötet nicht mehr,Tötet nicht mehr,0.0,2019.0,\N,\N,"Action,Crime"
13077,tt0013274,movie,Istoriya grazhdanskoy voyny,Istoriya grazhdanskoy voyny,0.0,2021.0,\N,94,Documentary
15172,tt0015414,movie,La tierra de los toros,La tierra de los toros,0.0,2000.0,\N,60,\N
15480,tt0015724,movie,Dama de noche,Dama de noche,0.0,1993.0,\N,102,"Drama,Mystery,Romance"
21267,tt0021617,movie,Arizona Territory,Arizona Territory,0.0,1950.0,\N,56,Western

In [15]:
# how many are tvmovie  vs movie
df_title_basics_filtered.groupby("titleType").count()

,tconst,primaryTitle,originalTitle,isAdult,startYear,endYear,runtimeMinutes,genres
titleType,,,,,,,,
movie,520432,520430,520430,520432,520432,520432,520432,520432
tvMovie,143608,143608,143608,143608,143608,143608,143608,143608

In [27]:
# lets look at a few 
tv_movie_filter = df_title_basics_filtered["titleType"] == "tvMovie"
after_1998_before_2023 = (df_title_basics_filtered["startYear"] >= 1998) & (df_title_basics_filtered["startYear"] <= 2023)

In [30]:
df_title_basics_filtered[tv_movie_filter & after_1998_before_2023].sort_values(by="startYear", ascending=False).head(50)

,tconst,titleType,primaryTitle,originalTitle,isAdult,startYear,endYear,runtimeMinutes,genres
6203909,tt25814780,tvMovie,Healing Drugs,Heilende Drogen,0.0,2023.0,\N,52,Documentary
6460869,tt27194076,tvMovie,Track Two,Toinen raide,0.0,2023.0,\N,53,Documentary
6966653,tt28870435,tvMovie,Mais que fait la police au cinéma,Mais que fait la police au cinéma,0.0,2023.0,\N,52,Documentary
6462067,tt27197920,tvMovie,Gustav Mahler: Sinfonie Nr. 2 'Auferstehung',Gustav Mahler: Sinfonie Nr. 2 'Auferstehung',0.0,2023.0,\N,92,Music
5989725,tt23785162,tvMovie,Sweet on You,Sweet on You,0.0,2023.0,\N,85,"Comedy,Drama,Romance"
6462054,tt27197895,tvMovie,Auf dem Seil über Dagestans Schluchten,Auf dem Seil über Dagestans Schluchten,0.0,2023.0,\N,\N,Documentary
6461654,tt27196841,tvMovie,House of Deadly Lies,House of Deadly Lies,0.0,2023.0,\N,97,Thriller
6972243,tt28938853,tvMovie,The Patriot Games Malaysia,The Patriot Games Malaysia,0.0,2023.0,\N,90,"Adventure,Drama,Game-Show"
6461399,tt27196002,tvMovie,Ice Age America,Amérique: la nouvelle histoire des premiers ho...,0.0,2023.0,\N,90,Documentary
6974473,tt28948711,tvMovie,Buds,Buds,0.0,2023.0,\N,25,Comedy
6461237,tt27195082,tvMovie,Love at First Lie,Love at First Lie,0.0,2023.0,\N,\N,Drama
6977404,tt28970314,tvMovie,"3 Captains, 3 Cups, 3 Stripes","3 Captains, 3 Cups, 3 Stripes",0.0,2023.0,\N,\N,Documentary
6977809,tt28972338,tvMovie,"Amb tots vostès, Joan Pera","Amb tots vostès, Joan Pera",0.0,2023.0,\N,\N,"Biography,Documentary"
6978286,tt28979155,tvMovie,Kazdý má svou pravdu,Kazdý má svou pravdu,0.0,2023.0,\N,141,Comedy
6979424,tt28990230,tvMovie,Chile: A Troublesome Legacy,"Chili, par la raison ou par la force",0.0,2023.0,\N,91,"Documentary,History"
6979805,tt28994468,tvMovie,A Via Sacra,A Via Sacra,0.0,2023.0,\N,\N,Documentary
6980833,tt28997100,tvMovie,Amish Stud: The Eli Weaver Story,Amish Stud: The Eli Weaver Story,0.0,2023.0,\N,85,"Crime,Drama,Thriller"
6966544,tt28870163,tvMovie,Kontrabass virtuos!,Kontrabass virtuos!,0.0,2023.0,\N,59,Music
6459837,tt27190880,tvMovie,Leif Ove Andsnes spielt Mozart,Leif Ove Andsnes spielt Mozart,0.0,2023.0,\N,44,Music
6982256,tt29005479,tvMovie,La belle étincelle,La belle étincelle,0.0,2023.0,\N,\N,Drama
6982273,tt29005539,tvMovie,Harry Potter : les secrets du phénomène,Harry Potter : les secrets du phénomène,0.0,2023.0,\N,87,Documentary
6982685,tt29007231,tvMovie,Bad Romance: The Vicky White Story,Bad Romance: The Vicky White Story,0.0,2023.0,\N,87,"Crime,Drama,Thriller"
6983097,tt29007820,tvMovie,Christmas at the Chalet,Christmas at the Chalet,0.0,2023.0,\N,84,Romance
6983851,tt29009043,tvMovie,Novios por navidad,Novios por navidad,0.0,2023.0,\N,\N,Romance
6984022,tt29009380,tvMovie,My Wife's Hidden Lover,Body in the Attic,0.0,2023.0,\N,89,"Drama,Thriller"
6459769,tt27190777,tvMovie,Mcaine. An Anagram of Cinema,Sir Michael Caine - Vom Arbeiterkind zum Holly...,0.0,2023.0,\N,53,"Biography,Documentary"
6985617,tt29025873,tvMovie,El sopar dels idiotes,El sopar dels idiotes,0.0,2023.0,\N,97,Comedy
6985625,tt29025890,tvMovie,For Evita. Una astracanada musical,For Evita. Una astracanada musical,0.0,2023.0,\N,\N,Musical
6985685,tt29026133,tvMovie,Young Fathers - Echoes with Jehnny Beth,Young Fathers - Echoes with Jehnny Beth,0.0,2023.0,\N,61,Music
6985704,tt29026252,tvMovie,Wrapped,Wrapped,0.0,2023.0,\N,25,Drama
6985829,tt29028458,tvMovie,Nyanners Lore: Commander Cat,Nyanners Lore: Commander Cat,0.0,2023.0,\N,\N,Comedy
6459754,tt27190752,tvMovie,Nofretete: Wem gehört die Schönheit?,Nofretete: Wem gehört die Schönheit?,0.0,2023.0,\N,53,"Documentary,History"
6462392,tt27199056,tvMovie,Lucky Hearts,Lucky Hearts,0.0,2023.0,\N,89,"Comedy,Drama"
6966530,tt28870127,tvMovie,Neapel - Stadt der Künste,Neapel - Stadt der Künste,0.0,2023.0,\N,53,Documentary
6942305,tt28777054,tvMovie,Akropolis - Beraubtes Symbol,Akropolis - Beraubtes Symbol,0.0,2023.0,\N,53,Documentary
6956520,tt28814289,tvMovie,Das neue Leben des Rappers Dr. Knarf,Das neue Leben des Rappers Dr. Knarf,0.0,2023.0,\N,30,Documentary
6943586,tt28778528,tvMovie,Vanished in Yosemite,Vanished in Yosemite,0.0,2023.0,\N,85,Thriller
6944014,tt28779627,tvMovie,Monster of the Week,Monster of the Week,0.0,2023.0,\N,190,Horror
6944335,tt28780388,tvMovie,Vivaldi unter Sternen - Die vier Jahreszeiten ...,Vivaldi unter Sternen - Die vier Jahreszeiten ...,0.0,2023.0,\N,41,Music
6947098,tt28788202,tvMovie,Úton a napsütötte hegy felé,Úton a napsütötte hegy felé,0.0,2023.0,\N,\N,Biography
6947106,tt28788257,tvMovie,56 | Z,56 | Z,0.0,2023.0,\N,71,Documentary
6948300,tt28793306,tvMovie,Ist die Rente noch sicher?,Ist die Rente noch sicher?,0.0,2023.0,\N,90,Documentary
6469592,tt27217467,tvMovie,Génération vidéo club,Génération vidéo club,0.0,2023.0,\N,52,Documentary
6950894,tt28802704,tvMovie,Schule am Meer - Familienbande,Schule am Meer - Familienbande,0.0,2023.0,\N,88,Drama
6950915,tt28802739,tvMovie,Reichsbürger - Innenansichten einer extremisti...,Reichsbürger - Innenansichten einer extremisti...,0.0,2023.0,\N,53,Documentary
6468620,tt27213554,tvMovie,Blood Trail,Blood Trail,0.0,2023.0,\N,\N,Western
6468525,tt27212784,tvMovie,Christmas at the Amish Bakery,Christmas at the Amish Bakery,0.0,2023.0,\N,85,Romance
6467883,tt27209804,tvMovie,Buying Back My Daughter,Buying Back My Daughter,0.0,2023.0,\N,88,"Drama,Thriller"
6467822,tt27209515,tvMovie,Don't Come Back - Dans les ruines de Mossoul,Don't Come Back - Dans les ruines de Mossoul,0.0,2023.0,\N,53,Documentary
6956425,tt28814061,tvMovie,TasteBuds with Crista Luedtke,TasteBuds with Crista Luedtke,0.0,2023.0,\N,23,Reality-TV